### ISSUE TITLE
 Campos Presupuesto dolares y Presupuesto pesos no poseen datos por default

### ISSUE THREAD

**Issue by c2ksoria** [c2ksoria/reservas_online#3]
![Issue con vaalores por default](https://github.com/user-attachments/assets/5edb5935-df6a-4840-aff9-c87f3fb1c8d7)
Cuando se crea una nueva reserva, los campos Presupuesto dolares y Presupuesto pesos no poseen datos por default, lo que a veces dificulta el proceso de carga; cuando no se ha sacado un presupuesto en alguna de las monedas; o simplemente relleno uno de los campos y el otro queda vacío. Esta última sitaución hace que al intentar almacenar la nueva reserva, de un error de campo incompleto; a fin de evitar esto deberíamos colocar los valores por defaul en cero.

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the Reservation model to set default values of zero for presupuesto_dolares and presupuesto_pesos fields to prevent errors when creating new reservations with incomplete budget information.

You can review changes in this commit: https://github.com/mnmnk43434/c2ksoria-reservas_online-3/commit/3f1c9ce7700e054ef203764c3c1b59dc9fa2016c.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by c2ksoria** [comment]
el resultado fue satisfactorio!
